spring.application.name=springboot_test2

app.path=classpath:/config/.properties
app.name=zhangsan
app.age=18
app.email=123456@163.com

spring.config.import=classpath:application-mysql.properties

mybatis.mapper-locations=classpath:mapper/*.xml
